Practiquitas
ERR-Z3R0/practices pull request #17
Opened 2023-04-04 16:01 UTC by Expana

Confime si ahí esta bien krnal

2023-04-04 16:34 UTC, EDUJOS requested changes
No es necesario crear un array y luego iterarlo en un blucle.

- [x] Verificar url
  - Cuando no sea url de Twitter retornar `false`
- [ ] Extraer id
- [ ] Devolver id

2023-04-04 16:34 UTC, EDUJOS commented on broken-code/one.js
> -// Escribe la función aquí
No elimines las url que te di, si te das cuenta una tiene la id pero otro tiene la id y `?s=20`. Estas url son las posibles url que el usuario le puede dar al programa.

2023-04-04 16:34 UTC, EDUJOS commented on broken-code/one.js
> +  for(let i = 0; i < listaUrlNumero; i++){
No es necesario crear un arreglo y un bucle porque el usuario te va a dar una sola url, no te confundas con las constantes. Esas constantes solo representan las distintas url que el usuario podría ingresar al programa, lo que el programa necesita es la id del tweet. Entonces lo que tienes que hacer es crear una función que verifique que la url sea de Twitter, extraer la id numérica que esta al final de la url `https://twitter.com/${user}/status/${id}` y devolver la id del tweet. Es decir tienes que extraer la id de la url

2023-04-04 16:34 UTC, EDUJOS commented on broken-code/one.js
> +  if (url.startsWith("https://twitter.com")){
Muy bien, aquí estas comprobando que la url sea de Twitter 👌

2023-04-04 17:00 UTC, EDUJOS commented
```js
function getId (url) {
   // Verificar Url
   if (!url.startsWith('https://twitter.com')) {
      return false // En este punto nuestra función getId devuelve falso y no continúa ejecutandose
   }
  // Verificar que la url sea de un tweet, es decir que se vea de la siguiente forma https://twitter.com/user/status/id
}

2023-04-06 05:50 UTC, Expana commented
Ya páseme de semestre inge

2023-04-06 05:50 UTC, Expana commented
Ya no quiero ser el único de 5to semestre en una clase de 2do semestre

2023-04-06 05:51 UTC, EDUJOS approved these changes
Good job bro!! 🥇

2023-04-06 05:51 UTC, merged